version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-env
      # To test the build of the image
      # args:
      #   - NODE_ENV=production
      #   - CONFIGURATION=production
      #   - RELEASE_VERSION=1.0.0
      #   - MQTT_HOST=localhost
      #   - MQTT_USER=user
      #   - MQTT_PWD=password
      #   - MQTT_PORT=8080
    command: ['npx', 'ng', 'serve', '--host', '0.0.0.0']
    ports:
      - 4200:4200
  vernemq:
    image: vernemq/vernemq:1.13.0-alpine
    ports:
      - '1883:1883' # MQTT
      - '8080:8080' # MQTT over websocket
    # you can exec `vmq-admin trace client client-id=<client-id>` if you want more tracing on what's happening
    # other useful commands are found here:
    #   https://docs.vernemq.com/live-administration/managing-sessions
    #   https://docs.vernemq.com/live-administration/retained-store
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
      DOCKER_VERNEMQ_USER_user: 'password'
      DOCKER_VERNEMQ_VMQ_PASSWD.password_reload_interval: 0
      DOCKER_VERNEMQ_LISTENER.tcp.allowed_protocol_versions: 3,4,5
      DOCKER_VERNEMQ_LOG.console.level: debug
    volumes:
      - vernemq-data:/vernemq/data/

volumes:
  vernemq-data:
