services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-env
      # To test the build of the image
    #      args:
    #       - NODE_ENV=production
    #       - CONFIGURATION=production
    #       - RELEASE_VERSION=1.0.0
    #       - MQTT_HOST=localhost
    #       - MQTT_USER=user
    #       - MQTT_PWD=password
    #       - MQTT_PORT=8084
    command: ['npx', 'ng', 'serve', '--host', '0.0.0.0']
    profiles:
      - app
    ports:
      - 4200:4200
  emqx:
    image: emqx/emqx:5.7.2
    ports:
      - '1883:1883' # MQTT over TCP
      - '8883:8883' # MQTT over SSL
      - '8083:8083' # MQTT over websocket
      - '8084:8084' # MQTT over secure websocket
      - '18083:18083' # dashboard
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log

volumes:
  emqx-data:
  emqx-log:
